### PR TITLE
Ability to change age of other characters

### PR DESCRIPTION
**Pull request by ddbb07**
Ability to change age of other characters and also a fix to the portrait in the set age window

### CODE REVIEW

**Comment by paige404** [comment]
Oh wow. This is a much requested feature though not one that I ever personally cared about. Happy to accept it in when it's done up already though.

Thanks for the work on this. I'll have to run some tests before merging of course but on first look your changes look great.

**Comment by paige404** [comment]
I've loaded up your fork as a separate mod for testing in its own playset. 

It looks like it works, but the localization appears to be broken. Genuinely unsure what's going wrong there, though.

When you test it on your own machine, does your interaction menu say "Grant immortality", or  "grant_immortality_interaction"? I'm getting the latter, and it doesn't happen on my current code.

**Comment by ddbb07** [comment]
I have no idea what was wrong, it worked fine for me earlier so i just reverted to an earlier version of the same file and now it works.

**Comment by paige404** [comment]
Ah sorry, Got tied up with stuff. I'll test out latest now.

**Comment by paige404** [comment]
Looks great, works great. I'll merge it in and release today.

The only problem I see is that setting immortality age doesn't do anything with characters that aren't immortal. Might look into hiding the interaction when the target isn't immortal. But I'm not gonna hold up the feature over that.

**Pull request merged**
