### PR TITLE
Update immortality.txt

### PR DESCRIPTION
**Pull request by ServitorXur**
**What I added:**
Basically made the immortal character un-killable by reducing murder scheme chances. 

An idea for future updates:

Had idea for AI checking if they're 
wounded or disfigured so they could heal themselves but did not implement it, just wanted to see what you thought.

### CODE REVIEW

**Comment by paige404** [comment]
I appreciate the PR! I think this one goes a bit overboard though. I can see the reasoning for reducing murder success, but I don't think all the hostile scheme resistance is necessary--there are many other hostile schemes besides murder. Not only should stuff like kidnapping and fabricating secrets be possible, but murder should _also_ be possible. Immortal does not mean unkillable.

Regarding the AI change, I don't actually want AI to fix their problems that way; if anyone feels _that_ strongly about an NPC's traits they can always debug menu it. If anything, I'm considering expanding that player decision into a more granular system. Sometimes you want some disfigurement. No reason I shouldn't be able to remove my cancer while remaining one-eyed, you know?

**Comment by ServitorXur** [comment]
Maybe make a 2nd trait for truly unkillable rulers? I'm getting into timelapses and its very frustrating when my immortal character dies of murder. and yeah my bad for all hostile schemes didn't realize that. and the AI thing was going along the same logic

**Comment by paige404** [comment]
I don't think murder scheme resistance would make you "truly unkillable". There are psychological events that can kill. You can be killed in battle. You can be killed in duels. You can be killed by events from other mods. I know of no way to make a ruler truly unkillable. It's part of why I've resisted this kind of change, because I cannot make that kind of promise to the user.

I am open to reducing murder scheme chances on immortals though. They should be _hard_ to kill, after all. Just nix the general hostile scheme protection.

**Comment by paige404** [comment]
Are you planning to adjust this PR soon? I have another PR merged in but have been holding off on releasing a new version in case this was going to be ready to merge right after.

**Comment by ServitorXur** [comment]
I just took out the hostile schemes stuff and changed it to murder

**Pull request merged**
