### PR TITLE
expand decisions to ck3 immortal trait

### PR DESCRIPTION
**Pull request by fabian-bienz**
where sensible.
adjust eunuch traits in restore body decision and interaction

### CODE REVIEW

**Comment by fabian-bienz** [comment]
I was wondering, if the interactions to grant / remove immortality should be expanded to include the vanilla immortal trait?
If so should this just be additional interactions or would and event be more user friendly?

**Comment by paige404** [comment]
I'm of two minds on including the vanilla immortal trait. But yeah, let's try it. Good PR, thank you. I'll cut a release shortly.

**Comment by fabian-bienz** [comment]
@paige404 sorry I didn't get that completely. 
Should I try to include the vanilla immortal trait as a character interaction?

**Comment by paige404** [comment]
Oh, I misunderstood the question I think. No, I don't think this mod needs an interaction to grant or remove the vanilla immortal trait. If you want that, you just buy it at character creation, that should be fine enough.

If you fix the redundant AND statements I'll go ahead and merge this.

**Comment by fabian-bienz** [comment]
Alright I fixed it.
I must have been going crazy yesterday, the additional wrapping around the OR block fixed a peculiar problem I encountered.
Said problem could not be reproduced today... 
Anyways, it's working as expected for me now.

**Pull request merged**
